env:
    DEFAULT_SERVER_VERSION: main
    DEFAULT_DURATION: 5m
    JUNIT_REPORT_PATH: junit-long-running.xml

name: "NATS Server - Long Running Tests"

agents:
  queue: "general-purpose"

steps:

- command: |
    nix-shell --run ./.buildkite/scripts/run-long-tests.sh ./.buildkite/shell.nix
  label: "Run tests (and publish results)"
